[workspace]
authors = ["Andrei Guliaev <andrei.guliaev@scilifelab.uu.se>"]
channels = ["conda-forge", "bioconda"]
name = "coverage_reports"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
render-v2 = "quarto render main_report.qmd --output \"coverage_report_v2_$(date +%Y-%m-%d_%H-%M-%S).html\" --execute-params params_v2.yml"
render-v1 = "quarto render main_report.qmd --output \"coverage_report_v1_$(date +%Y-%m-%d_%H-%M-%S).html\" --execute-params params_v1.yml"
test = "Rscript -e 'testthat::test_dir(\"tests\")'"
style = "Rscript -e 'styler::style_dir(\"R\")' -e 'styler::style_file(\"main_report.qmd\")' -e 'styler::style_dir(\"tests\")'"
lint = "Rscript -e 'if(length(lintr::lint_dir(\"R\")) > 0) stop(\"Linting errors found!\")'"

[dependencies]
r-base = ">=4.5.2,<4.6"
r-tidyverse = ">=2.0.0,<3"
r-tidyr = ">=1.3.2,<2"
r-plotly = ">=4.12.0,<5"
r-dt = ">=0.34.0,<0.35"
r-ggplot2 = ">=4.0.2,<5"
r-purrr = ">=1.2.1,<2"
r-tibble = ">=3.3.1,<4"
bedtools = ">=2.31.1,<3"
r-languageserver = ">=0.3.16,<0.4"
r-httpgd = ">=2.0.4,<3"
radian = ">=0.6.15,<0.7"
quarto = ">=1.8.27,<2"
r-rmarkdown = ">=2.30,<3"
r-knitr = ">=1.51,<2"
r-jsonlite = ">=2.0.0,<3"
r-here = ">=1.0.2,<2"
r-styler = ">=1.11.0,<2"
r-lintr = ">=3.3.0_1,<4"
r-testthat = ">=3.3.1,<4"
